### ISSUE TITLE
compile error on Ubuntu 18

### ISSUE THREAD

**Issue by vsmart** [rustbridge/Rusty-Snake-Book#4]
👋 Hi all, 
Thank you for creating this tutorial! I'm currently stepping through the tutorial in prep for the rust bridge workshop. 

Just a heads up that I had a compile error* right at the beginning of the tutorial on Ubuntu 18, with latest rust (1.39) installed. 

I had to `sudo apt-get install libsdl2-dev` to get this working. 

Might be worth including on the first install slide!

* I don't have the stack trace handy anymore - it was a C trace referencing sdl.  

cc @Mirabellensaft

**Comment by Mirabellensaft** [comment]
Thank you!
